# Generated by Django 5.1.3 on 2024-11-26 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_auditable_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='users_usera_user_id_4e2d1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='users_usera_timesta_aabea0_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='users_usera_ip_addr_3e13d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_role_de8a85_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_user_id_f90df1_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_created_72cdd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_emp_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='users_userp_role_c31a7e_idx',
            old_name='users_userp_role_idx',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='object_id',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='deactivated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='users_usera_user_id_832d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action'], name='users_usera_action_2472c4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['status'], name='users_usera_status_455042_idx'),
        ),
    ]
